SELECT 
    r.REST_ID, 
    r.REST_NAME, 
    r.FOOD_TYPE, 
    r.FAVORITES, 
    r.ADDRESS, 
    ROUND(AVG(rv.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS r
INNER JOIN REST_REVIEW AS rv ON r.REST_ID = rv.REST_ID
WHERE r.ADDRESS LIKE '서울%'
GROUP BY r.REST_ID, r.REST_NAME, r.FOOD_TYPE, r.FAVORITES, r.ADDRESS
ORDER BY SCORE DESC, r.FAVORITES DESC