-- 코드를 입력하세요
--  경기도에 위치한
-- 냉동시설 여부가 NULL인 경우, 'N'으로 출력
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N')
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
-- 창고 ID를 기준으로 오름차순 정렬
ORDER BY WAREHOUSE_ID