-- 코드를 입력하세요
-- PRODUCT_CODE 앞 두자리 기준으로 카테고리 나누기
-- 카테고리별 갯수 세기
SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(PRODUCT_CODE) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE, 1, 2)
ORDER BY CATEGORY