-- 코드를 입력하세요
SELECT u.TITLE, u.BOARD_ID, ur.REPLY_ID, ur.WRITER_ID, ur.CONTENTS, DATE_FORMAT(ur.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS u
INNER JOIN USED_GOODS_REPLY AS ur ON u.BOARD_ID = ur.BOARD_ID
WHERE YEAR(u.CREATED_DATE) = 2022 AND MONTH(u.CREATED_DATE) = 10
ORDER BY ur.CREATED_DATE ASC, u.TITLE ASC;
